      name: setup-go
        uses:setup
          go-version:1.16
        uses: actions/checkout@v3

      name: Show Docker containers
        run: docker ps -a
      name: Show databases for root user
        run: mysql --protocol=tcp -h localhost -P 3306 -u root -ppassword -e "SHOW DATABASES"
      name: Set up MySQL
        run: sudo /lib/systemd/systemd-sysv-install enable mysql
             sudo systemctl enable mysql.service
             sudo systemctl start mysql.service
      name: Run sample.sql
        run: |
          mysql --protocol=tcp -h localhost -P 3306 -u root -ppassword -e "$(cat $(find ./ -name sample.sql))"
      name: Show created tables
        run: mysql --protocol=tcp -h localhost -P 3306 -u root -ppassword -e "USE sampleDB"
             mysql --protocol=tcp -h localhost -P 3306 -u root -ppassword -e "SHOW TABLES"
      name: Insert data into user table
        run: sudo /lib/systemd/systemd-sysv-install enable mysql
             sudo systemctl enable mysql.service
             sudo systemctl start mysql.service
             sh ./.github/scripts/sample.sh
      name: Check inserted data
        run: mysql --protocol=tcp -h localhost -P 3306 -u root -ppassword -e "USE sampleDB"
             mysql --protocol=tcp -h localhost -P 3306 -u root -ppassword -e "SELECT * FROM user"


